#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

wclean $targetType specie
wclean $targetType thermophysicalProperties

wclean $targetType basic
wclean $targetType reactionThermo
wclean $targetType laminarFlameSpeed
wclean $targetType chemistryModel
wclean $targetType barotropicCompressibilityModel

wclean $targetType solidThermo

# ----------------------------------------------------------------- end-of-file
