#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#~ cp -ar constant/* constantBAC

cleanCase

rm -rf 0
#~ rm -rf processor*
#~ rm -rf constant/*
#~ cp -ar constantBAC/* constant
rm -f *.obj

# ----------------------------------------------------------------- end-of-file
