#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

#~ cp -ar constant/* constantBAC

rm -rf constant/boundaryData*

cleanCase

rm -rf 0
rm -f *.obj

rm -f *.pyData                                                          #remove all the saved matrices
rm -f pyVisMat/*                                                        #clear the pyVisMat outputs



# ----------------------------------------------------------------- end-of-file
