#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0

mkdir 0
cp -rf 0.org/* 0

mkdir dynamicCode

# create geometry
runApplication blockMesh

# create .OpenFOAM file
paraFoam -touch

runApplication topoSet

runApplication decomposePar

# add reactive cell zone 
# runParallel snappyHexMesh -overwrite
#runApplication snappyHexMesh -overwrite
# runParallel snappyHexMesh -overwrite

# rm -rf processor*/*/cellLevel
# rm -rf processor*/*/pointLevel
# rm -rf */cellLevel
# rm -rf */pointLevel

# mv log.decomposePar log.decomposePar1
# decompose
# runApplication decomposePar -fields
# runApplication decomposePar 

runParallel reactingHetCatSimpleFoamFC
mv log.reactingHetCatSimpleFoamFC log.reactingHetCatSimpleFoamFC2
runParallel reactingHetCatSimpleFoamFC

# runParallel renumberMesh -overwrite
# add reactive cell zone 
# runApplication topoSet

#application=`getApplication`
#runParallel $application
#mv log.$application log2.$application
#runParallel $application
#runApplication reconstructPar -latestTime
#
#postProcess -func integrace -latestTime > log.integrace
#runApplication intSrcSphere
