#!/bin/bash
# make sure about my position
cd $(dirname $0)

# just to have notion
date "+%d/%m/%Y %T"

# import openfoam
source /opt/openfoam6/etc/bashrc
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clear old IC
rm -rf 0

# create base mesh 
runApplication blockMesh

# create files for postprocessing
paraFoam -touch

# run checkMesh
runApplication checkMesh -allGeometry -allTopology
