#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0

mkdir 0
cp -rf 0.org/* 0

runApplication blockMesh
runApplication decomposePar
runParallel snappyHexMesh -overwrite -dict system/snappyHexMeshDictIntraTrans
runApplication reconstructPar
runApplication topoSet

mv log.decomposePar log2.decomposePar
mv log.reconstructPar log2.reconstructPar

rm processor* -rf

runApplication decomposePar
application=`getApplication`
runParallel $application
mv log.$application log2.$application
runParallel $application
runApplication reconstructPar

runApplication postProcess -func 'graphCellFace(start = (0 0 0), end = (1 0 0), fields=(CO))'
runApplication intSrcSphere

rm processor* -rf