#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0

mkdir 0
cp -rf 0.org/* 0

# create geometry
runApplication blockMesh

# add reactive cell zone 
runApplication snappyHexMesh -overwrite -dict system/snappyHexMeshDictIntraTrans

# add reactive cell zone 
runApplication topoSet

paraFoam -touch

runApplication decomposePar
application=`getApplication`
runParallel $application
mv log.$application log2.$application
runParallel $application
runApplication reconstructPar

rm processor* -rf

runApplication postProcess -func 'graphCellFace(start = (0 0 0), end = (1 0 0), fields=(CO))'

runApplication intSrcSphere