#!/bin/bash
# Name of the job
#SBATCH -J 10_zahus_2.5e-3
# Partition to use
#SBATCH -p Mshort
# Time limit. Often not needed as there are defaults, 
# but you might have to specify it to get the maximum allowed.
# time: 24hours
#SBATCH --time=2-00:00:00
# Number of processes
#SBATCH -n8
# Do NOT use some nodes
##SBATCH --exclude=kraken-m[1-7,9]
##SBATCH --nodelist=kraken-m9

# load openfoam
module load openfoam-org/8-10.3.0
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Clear old IC
rm -rf 0

# create base mesh
runApplication blockMesh

# run checkMesh
runApplication checkMesh -allGeometry -allTopology

# copy IC
mkdir -p 0
cp -rf 0.org/* 0

# create files for postprocessing
paraFoam -touch

# run potentialFoam
runApplication potentialFoam

# decompose the case
runApplication decomposePar

# get the solver application
application=`getApplication`

# run the solver
srun -n8 $application -parallel >> log.$application

# reconstruct the case
runApplication reconstructPar
