#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0

mkdir 0
cp -rf 0.org/* 0

# create geometry
runApplication blockMesh

# add reactive cell zone 
runApplication snappyHexMesh -overwrite -dict system/snappyHexMeshDictIntraTrans

# add reactive cell zone 
runApplication topoSet

paraFoam -touch

application=`getApplication`
runApplication $application

runApplication postProcess -func 'graphCellFace(start = (0 0 0), end = (1 0 0), fields=(CO))'

runApplication intSrcSphere